# Generated by Django 4.2.7 on 2026-03-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_and_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_keywords',
            field=models.TextField(blank=True, help_text='Extra search terms, e.g. face wash cleanser oily skin'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, help_text='e.g. Lip Liner, BB Cream, Anti-Aging', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated keywords, e.g. matte, waterproof, spf'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
